<!DOCTYPE html>
<html>
<?php
  $t = "5x5x5";
  include 'head.php';
?>

<body>
<h1 class="rmcTitle">RUBIKS MY CUBE</h1>
<?php
  include 'menu.php';
?>

 <div id="ham">
   <img src="i/ham.png">
 </div>
 <div id="pageContent">
  <p>**I am assuming you already know and understand how to solve the four by four.  If you do not please learn <a href="four.html">here</a>.   There will be multiple references to the four by four rubik's revenge,  and it is necessary to be able to solve it.**</p>
  <h1 class="sTitle">PART ONE - CENTERS</h1>
  <iframe style="float: right; margin: 10px; position: relative; top: 10px;" width="480" height="364" src="https://www.youtube.com/embed/AFmDhcIYBBE" frameborder="0" allowfullscreen></iframe>
  <p>For the purpose of this tutorial, I will be using white as the top color.  You may use whichever color you wish, just keep in mind I will be referring to white as the top color.  Just as the four by four,  we will be solving the centers.  To accomplish this we will make strips of of the white center pieces, then put them together.  First, we will make a 'block' of white, which will be a two by three rectangle, then make a one by three strip, and put them together.  For that, we make a two by one block on the center by moving one of the center pieces into position.  Now we make two more two by one blocks and put them next to it, forming the 'block'.  Now, we use the remaining white pieces(not part of the two by three block) to make a single one by three piece.  We put it together by moving the outer layers, so that when we move the inner layers on the side, they line up together.  Now we make the line verticle, using the white site a a reference point.  This will allow us to move the top, bring the white line up,  and push it up to connect the white centers.  Now we can move on to the yellow centers.  We will be using the same techniques as the four by four, pushing a piece in, turning the top, and bringing reversing the
damage we have done by re-connecting the white face.  With that,  we will connect the yellow center piece with one of the yellow pieces,  turn the top, and turn down the side we disrupted.  Now in the middle layer, we built another two by one block.  Put the pieces together, as shown in the video, and push the two by one to complete the two by three block.  But as you can tell, if we push the white back in to reconnect it,  we will destroy what we've already done.  So we just turn the yellow face so that when we turn the white back, it brings down the part that is not the two by three block.  Now we build the last one by two strip in the middle.  So we turn the faces so that when we try to connect the cubies, it makes the one by two strip.  By putting it up, we have made the two by three 'block'.  Now we turn the middle layers so that we have made a single one by three strip.  To get it in, we line it up with a yellow line, so that when we bring it up, it replaces an entire line of yellow.  This is so that when we turn the top twice, and fix the white, the yellow center is solved.  The next part is pretty much intuitive, and if you can solve the four by four you shoud be able to make the next center.  Now you must (also intuitivly) solve another center, not opposite the one you just recently solced.  Again, use the four by four methods.  The final two centers are a little tricky, so they will be gone over.  The method is basically the same as the yellow side,  making the two by three block and also making sure we don't mess up any of the other centers, by reversing everything we do.  Now it's intuitive again(groan...) and when you get the two almost solved sides(with just one piece left of each color), you can continue reading this how-to.  Ok, assuming you have done my previous instructions, the next step is very simple.  To set it up, we put the two corners that are not fixed into the top right positions(in the top face it will actually be the bottom-right).  Now you lift the right inner up,   turn the top once to the right,  and then bring the right back down once.  Now you make the two one by three lines you have just made parralell to each other,  then bring the line that need to go up up, and turn the top twice, and bring the same side you brought up back down again.  This will solve the centers.  Now we can move on to...</p>
  <h1 class="sTitle">PART TWO - EDGES</h1>
  <p>Notice that there are three different edge pieces, like the two on the four by four.  There is the one in the middle, and the 'wings' on the side.  To get the entire edge, we will be putting the wings relative to the center cubie.  So we position the cubies so that they are on the same side, but opposite and flipped to each other.  This will allow us to put the cubie in just like in the four by four; bringing the cubie down to match the center piece, moving the side with the cubies to the right,  replacing the cubies with one of the pairs around it, bringing the side back so that we can reconnect the center pieces.  We will do this for the entire cube.  One important note:  make sure you don't replace the edge you're solving with one that matters if you break it up; as he says in the video, 'replace it with garbage pieces'.  If you connect the pieces, you may inevidably run into a case where the pieces are in the right spot, but are oriented incorrectly.  This is the five by five's version of... (if you didn't get this, skip to the last sentence of the paragraph below)</p>
  <h1 class="sTitle">PART THREE - PARODY</h1>
  <p>There are two parody cases: one where there are two whole edges that have one part of each other, and one where there is only one edge that has it's own cubie 'wing' pieces, but they're flipped.  For the first case we have to make it so that the piece on the other side is going to go down into the "wrong" spot on the other piece, by putting it above it.  This will give you more broken edges, which is good.  As the next step is difficult to explain in writing, please refer to the video (26:40), and watch for about a minute.  You will now have the other parody.  To solve this we must use an algorithm; which is almost the exact same as the four by four, if you ignore the center layer.  So we position the "parodied" edge so that it's facing our face,  bring down the right inner layer, turn the top twice,  bring down the left inner layer, turn the front twice, bring the left inner layer back up, turn the front twice, pause for breath,  bring the right inner layer down twice,  turn the top twice,  lift the right up once, turn the top twice, bring the right down, and turn the top twice, pause for a bigger breath, more of a gasp really,  turn the front twice, the right inner layer twice, and the front twice again.  Now you have solved parody.  You will now solve it like a regular three by three.</p>
 </div>
 </body>
</html>